// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_17oZKXPLR7fvqtAwMY8brJ-Rz2cM_U',
    appId: '1:604283233775:web:54851558bf2bca9263021a',
    messagingSenderId: '604283233775',
    projectId: 'fooder-march-10-year-23',
    authDomain: 'fooder-march-10-year-23.firebaseapp.com',
    storageBucket: 'fooder-march-10-year-23.appspot.com',
    measurementId: 'G-C08JFJ0YG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdcg7O3DXRQR9Hl13OmLJUWr2vthgE9oA',
    appId: '1:604283233775:android:1c6579360e2bba7263021a',
    messagingSenderId: '604283233775',
    projectId: 'fooder-march-10-year-23',
    storageBucket: 'fooder-march-10-year-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcLVY6-thH0vQP79voWxsX4AM4dutW3bg',
    appId: '1:604283233775:ios:33e397e2ed6a369763021a',
    messagingSenderId: '604283233775',
    projectId: 'fooder-march-10-year-23',
    storageBucket: 'fooder-march-10-year-23.appspot.com',
    iosClientId: '604283233775-1m3up907mdld19h7klcc9miil7j2jerr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );
}
